on:
  workflow_call:
    inputs:
      store-artifact:
        description: 'Whether the built artifact should be stored'
        default: false
        required: false
        type: boolean
      artifact-name:
        description: 'Name of the artifact, defaults to `built-app`'
        default: built-app
        required: false
        type: string

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Archive build artifacts
        if: ${{ inputs.store-artifact }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.artifact-name }}
          path: ./build
          retention-days: 3 # we only store these for 3 days because they're almost always immediately used