name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - feature/fix-pipeline-empty # todo: only for testing

jobs:
  build:
    name: Check Build
    uses: ./.github/workflows/build.yml
    with:
      store-artifact: true
      artifact-name: built-app

  deploy:
    permissions:
      contents: write
    needs:
      - build
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: built-app
          path: ./build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
