name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  deploy:
    permissions:
      contents: write
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ./app
      - name: Build website
        run: npm run build
        working-directory: ./app


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /app/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
