name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Check Build
    uses: ./.github/workflows/build.yml

  deploy:
    permissions:
      contents: write
    needs:
      - build
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
